# Generated by Django 5.0.3 on 2024-03-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Limbs',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='people_collection.people')),
                ('arm', models.IntegerField()),
                ('leg', models.IntegerField()),
                ('feet', models.IntegerField()),
                ('hands', models.IntegerField()),
            ],
        ),
    ]
